### ISSUE TITLE
Prestashop installation fails with Oops message

### ISSUE THREAD

**Issue by akram** [PrestaShop/docker#16]
When having a look at the log, I see this:

````
10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
172.17.0.1 - - [16/Jun/2016:16:02:14 +0000] "GET /install/index.php?compile_templates=1&bo=0 HTTP/1.1" 500 185 "http://shop.p.com/install/index.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36"
[Thu Jun 16 16:02:14.024989 2016] [:error] [pid 554] [client 172.17.0.1:46909] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/var/www/html/themes/default-bootstrap/): failed to open dir: No such file or directory' in /var/www/html/tools/smarty/sysplugins/smarty_internal_utility.php:68\nStack trace:\n#0 /var/www/html/tools/smarty/sysplugins/smarty_internal_utility.php(68): RecursiveDirectoryIterator->__construct('/var/www/html/t...')\n#1 /var/www/html/tools/smarty/Smarty.class.php(1440): Smarty_Internal_Utility::compileAllTemplates('.tpl', false, 0, NULL, Object(SmartyCustom))\n#2 /var/www/html/install/controllers/http/smarty_compile.php(42): Smarty->compileAllTemplates('.tpl', false)\n#3 /var/www/html/install/classes/controllerHttp.php(96): require_once('/var/www/html/i...')\n#4 /var/www/html/install/index.php(31): InstallControllerHttp::execute()\n#5 {main}\n  thrown in /var/www/html/tools/smarty/sysplugins/smarty_internal_utility.php on line 68,
```

**Comment by DevNIX** [comment]
Seems like the `/var/www/html/themes/default-bootstrap` doesn't exists?

**Comment by Quetzacoalt91** [comment]
Indeed, I think this is because of this.

Please not that when you enable a volume, the content in the container is flushed and then replaced by the content on your host.
In consequence, if your link you theme folder to a empty one in your host ... It will be empty in the container as well.

I close this issue because it is related to a non-existing default-bootstrap folder on the host. Nothing needs to be changed in the docker image.

Best regards
