### ISSUE TITLE
Installing with the variable PS_INSTALL_AUTO=1 will not start the container automatically

### ISSUE THREAD

**Issue by quantum-llama** [PrestaShop/docker#73]
We came up with the idea, to run a long command and set everything up precisely at once without spending time with configuration over and over again, but

`sudo docker run -ti --name prestashop_test -p 8080:80 -d -e PS_INSTALL_AUTO=1 -e PS_FOLDER_ADMIN=admin_test -e PS_FOLDER_INSTALL=install_test prestashop/prestashop`

will fail to start automatically.

If I remove the `-e PS_INSTALL_AUTO=1 ` it works perfectly fine, spins up, but I have to install it manually.

Do you have any solution to this issue?

Thanks in advance!

**Comment by Quetzacoalt91** [comment]
Hello,

When you ask your PrestaShop container to be installed automatically, it requires a working SQL connection.
You will see if you remove the `-d` parameter that the container loops on "Waiting for MySQL connection ...". In order to install your PrestaShop automatically, you need to tell him what is the server address and what are the credentials to use.

Here are the parameters needed:
* **DB_SERVER**: If set, the external MySQL database will be used instead of the volatile internal one *(default value: localhost)*
* **DB_USER**: Override default MySQL user *(default value: root)*
* **DB_PASSWD**: Override default MySQL password *(default value: admin)*
* **DB_PREFIX**: Override default tables prefix *(default value: ps_)*
* **DB_NAME**: Override default database name *(default value: prestashop)*

**Comment by quantum-llama** [comment]
Hello Quetzacoalt91!

After providing the details, and removing the -d switch it still hangs-up on the MySQL connection.

I tried the following code:

`sudo docker run -ti --name prestashop_test -p 8080:80 -e PS_INSTALL_AUTO=1 -e PS_FOLDER_ADMIN=admin_test -e PS_FOLDER_INSTALL=install_test -e DB_SERVER=127.0.0.1 -e DB_USER=greg -e DB_PASSWD=gregsPw11 -e DB_PREFIX=ps15test_ -e DB_NAME=prestashop prestashop/prestashop:1.5`

but no luck.

I tested my login credentials, with `mysql -h 127.0.0.1 -u greg -p`, then feeding the password, and they were correct.

Can you advise me how to proceed with the debugging process?

Best Regards,
Greg

**Comment by quantum-llama** [comment]
Hello Quetzacoalt91!

Thank you for your help,  managed to make the auto-install work, but I bumped into another issue.

* Installing PrestaShop, this may take a while ...
Database "presta15_test" dropped
**PHP Fatal error:  Uncaught exception 'PrestaShopException' with message 'Property Order->id_address_delivery is empty' in /var/www/html/classes/ObjectModel.php:837**
Stack trace:
#0 /var/www/html/classes/ObjectModel.php(255): ObjectModelCore->validateFields()
#1 /var/www/html/classes/order/Order.php(277): ObjectModelCore->getFields()
#2 /var/www/html/classes/ObjectModel.php(596): OrderCore->getFields()
#3 /var/www/html/classes/order/OrderHistory.php(445): ObjectModelCore->update()
#4 /var/www/html/installtest5/classes/xmlLoader.php(437): OrderHistoryCore->add(true, false)
#5 /var/www/html/installtest5/classes/xmlLoader.php(310): InstallXmlLoader->createEntity('order_history', 'order_history_1', 'OrderHistory', Array, Array)
#6 /var/www/html/installtest5/classes/xmlLoader.php(214): InstallXmlLoader->populateEntity('order_history')
#7 /var/www/html/installtest5/models/install.php(716): InstallXmlLoader->populateFromXmlFiles()
#8 /var/www/html/installtest5/controllers/console/process.php(228): InstallModelInstall->installFixtures(N in /var/www/html/classes/ObjectModel.php on line 837

The shop is working, but I'm not able to add products, nor it has the default products.

The error I'm getting when I'm trying to add a product is: "An error occurred while creating an object. product"

Before that the shop was expressed it's hatred against the sql_mode variable, which I have changed with the following line, resolving the problem:

`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')); `

Could you please advise what could have gone wrong?


Best Regards,
Gregory

**Comment by Quetzacoalt91** [comment]
Hello,

Which SQL server are you using ?

**Comment by quantum-llama** [comment]
Hello,

The result of `SELECT VERSION();` in mysql is 5.7.18-0ubuntu0.16.04.1

**Comment by Quetzacoalt91** [comment]
It seems this version is incompatible with PrestaShop prior version 1.6.1.6.

You will have to use MySQL 5.5 or 5.6 in order to go further in the installation.

**Comment by andpolo96** [comment]
I recomment use docker-compose for an sucessfull instalation.  https://github.com/PrestaShop/PrestaShop/blob/develop/docker-compose.yml
